{
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": { 
        "standard": { 
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
        },
    },
    "handlers": { 
        "default": { 
            "level": "INFO",
            "formatter": "standard",
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stdout",  # Default is stderr
        },
    },
    "loggers": { 
        "": {  # root logger
            "handlers": ["default"],
            "level": "INFO",
            "propagate": True
        },
        "my.packg": { 
            "handlers": ["default"],
            "level": "WARN",
            "propagate": False
        },
    } 
}